server:
   port: 1111

# ===================================================================
# 服务注册中心
# ===================================================================
eureka:
  instance:
    hostname: localhost
    appname: ${spring.application.name}
    instanceId: ${eureka.instance.appname}-${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka
