# ===================================================================
#
#                         开发环境配置文件
#
# ===================================================================
server:
   port: 8080

# ===================================================================
# web应用信息查看
# ===================================================================
management:
  security:
    enabled: false