# ===================================================================
# 激活配置（可选dev、prod、test)
# ===================================================================
spring:
  profiles:
    active: dev
  application:
    name: caller