# ===================================================================
#
#                         开发环境配置文件
#
# ===================================================================
server:
   port: 8081

# ===================================================================
# web应用信息查看
# ===================================================================
management:
  security:
    enabled: false

# ===================================================================
# 服务注册中心
# ===================================================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka,http://localhost:1112/eureka
